
 * Waiting in queue... 
 * Loading list of packages.... 
The following packages have to be installed:
 gnuplot-5.2.4-1.el8.x86_64	A program for plotting mathematical expressions and data
 gnuplot-common-5.2.4-1.el8.x86_64	The common gnuplot parts
 qt5-qtsvg-5.12.5-1.el8.x86_64	Qt5 - Support for rendering and displaying SVG

 * Waiting in queue... 
 * Waiting for authentication... 
